services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=hockeyDB
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    restart: always
    command: ['--bind_ip_all']

volumes:
  mongodb_data:
