version: '3.8'

services:
  mongo-primary:
    image: mongo:latest
    container_name: mongo-primary
    ports:
      - "27017:27017"
    volumes:
      - mongo-primary-data:/data/db
    networks:
      - mongo-cluster
    command: "--replSet rs0 --bind_ip_all"

  mongo-secondary1:
    image: mongo:latest
    container_name: mongo-secondary1
    volumes:
      - mongo-secondary1-data:/data/db
    networks:
      - mongo-cluster
    command: "--replSet rs0 --bind_ip_all"

  mongo-secondary2:
    image: mongo:latest
    container_name: mongo-secondary2
    volumes:
      - mongo-secondary2-data:/data/db
    networks:
      - mongo-cluster
    command: "--replSet rs0 --bind_ip_all"

networks:
  mongo-cluster:

volumes:
  mongo-primary-data:
  mongo-secondary1-data:
  mongo-secondary2-data:
